import type { Metadata } from "next";
import { pretendard } from "./fonts";
import "./globals.css";
import DialogProvider from "@/components/dialogs/dialog-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body className={`${pretendard.variable} antialiased`}>
        {children}
        <DialogProvider />
      </body>
    </html>
  );
}
