import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import DialogProvider from "@/components/dialogs/dialog-provider";
import ToastProvider from "@/components/toast/toast-provider";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body className={`${pretendard.variable} antialiased`}>
        <div className="max-w-(--viewport-size) mx-auto bg-site-black">
          {children}
        </div>
        <DialogProvider />
        <ToastProvider />
      </body>
    </html>
  );
}
